### ISSUE TITLE
Option to remove the flickering effect?

### ISSUE THREAD

**Issue by syltendo** [obsidian-dot-dev/openFPGA-Vectrex#1]
II suppose the flickering effect is trying to recreate the original display, but an option to play with "clean" graphics would be nice too.

**Comment by obsidian-dot-dev** [comment]
Removing the flicker entirely isn't possible, unfortunately -- it's just a feature of the hardware (beam scanning is asynchronous).  In the settings there's an option called "persistence".  This controls the amount of flicker; higher values are higher flicker, lower values are less flicker-y, at the expense of more blurring between frames.

**Comment by syltendo** [comment]
Thanks for the explanation!
