### ISSUE TITLE
Additional option: autoload overlay

### ISSUE THREAD

**Issue by pinballgithub** [obsidian-dot-dev/openFPGA-Vectrex#2]
Could you implement an option in the settings "autoload overlay". If enabled, an overlay with the same filename as the rom is loaded. If an overlay with this name is no existing, no overlay is loaded. If the option is disabled, rom and overlay are selected separately.

**Comment by obsidian-dot-dev** [comment]
I'm going to add a version of auto-loading in the next release -- stay tuned.

**Comment by obsidian-dot-dev** [comment]
v0.9.1 has added auto-loading support via "<instance>.json" files.  There are jsons for each of the officially-released games.
