### ISSUE TITLE
Not loading roms

### ISSUE THREAD

**Issue by costarc** [obsidian-dot-dev/openFPGA-Vectrex#4]
Select Run and can browse the list of roms
Select a rom (.vec)

Analogue display only "Back" and I can only continue browsing - game is not loaded.

Maybe the Vectrex bios is in the wrong place ?  Where is the right place for BIOS: Assets/common  or Assets/obsidian.Vectrex ?

My analogue firmware updated to latest release.
Thanks.

**Comment by obsidian-dot-dev** [comment]
You don't need a BIOS, but you do need overlay files.  This is the second file picker that is shown after choosing your rom.  Overlays have a ".ovr" extension and need to be placed alongside the roms.  You can get the overlays from the MisSTer Vectrex repo, which contains an archive of .ovr file overlays in the correct format.  The link to that repo is in the main README.md.

**Comment by costarc** [comment]
That was it. I did not figure overlays was required.
