### ISSUE TITLE
Improve initial file load user experience 

### ISSUE THREAD

**Issue by b-mag** [obsidian-dot-dev/openFPGA-Vectrex#7]
Problem: starting games is frustrating for both new users and those who do not want to use overlays. 

Solution: if a user selects either a .Vec or .bin do not ask them to load an overlay. Let people select overlays once game starts. 

Reasoning:1) default behavior of all other cores behaves this way. 2) A quick Google search will show how many new users were confused by being forced to select an overlay.

**Comment by obsidian-dot-dev** [comment]
Fair point.  I can change the default to not *require* an overlay, which will provide the behavior you're looking for.

**Comment by b-mag** [comment]
That sounds great.   Thank you.

**Comment by obsidian-dot-dev** [comment]
v0.9.3 release no longer requires loading of overlays, although both can still be loaded together via .json files.
